config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products, only: %i[destroy]
  root to: 'pages#home'

  # get '/users/sign_out' => 'devise/sessions#destroy'

  get 'my_products', to: 'products#my_products'

  resources :products do
    resources :bookings, only: %i[new create destroy]

    collection do
      get :search
    end

    member do
      get :reviews
    end

    resources :bookings, only: %i[new create destroy]
  end

  resources :bookings, except: [ :new, :index, :create ] do
    resources :reviews, only: [ :new, :create ]
  end

  resources :reviews, except: [ :new, :create ]

  get '/bookings', to: 'bookings#index'

  get '/error', to: 'errors#not_found'

  # get "*path", to: redirect("/error")
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :product

  has_one :review, dependent: :destroy

  validates :total_price, presence: true
  validates :first_day_of_booking, presence: true
  validates :last_day_of_booking, presence: true

  before_save :calculate_total_price

  private

  def calculate_total_price
    self.total_price = (last_day_of_booking - first_day_of_booking).to_i * product.price_per_day
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_booking, only: %i[show edit update destroy]
  before_action :set_product, only: %i[new create]

  def index
    @bookings = Booking.all
    @my_bookings = Booking.where(user_id: current_user.id)
    # @my_products_booked = current_user.products.map(&:bookings).productten
  end

  def new
    @booking = Booking.new
  end

  def show
    # @total_price = (@booking.last_day_of_booking - @booking.first_day_of_booking).to_i * @booking.product.price_per_day
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = @user.id
    @booking.product_id = @product.id
    @booking.total_price = ((@booking.last_day_of_booking - @booking.first_day_of_booking).to_i) * @product.price_per_day
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def edit
  end

  def update
    new_id = @booking.product_id
    @product = Product.find(new_id)
    @booking.update(booking_params)
    @booking.total_price = ((@booking.last_day_of_booking - @booking.first_day_of_booking).to_i) * @product.price_per_day
    # authorize @booking
    if @booking.save
      redirect_to booking_path
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to booking_path
  end

  private

  def booking_params
    params.require(:booking).permit(:first_day_of_booking, :last_day_of_booking)
  end

  # def total_price
  #   @product.price_per_day * @booking.date_booked.length
  # end

  # def total_price(booking, product)
  #   (booking.last_day_of_booking - booking.first_day_of_booking).to_i * product.price_per_day
  # end

  def set_product
    @product = Product.find(params[:product_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_user
    @user = current_user
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/edit.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h2 class="display-1 pt-5">Modifier votre reservation</h2>
  </div>
</div>

<div class="container d-flex flex-column p-4 mb-4 shadow mx-auto">
    <div class="row">
      <%= simple_form_for [@booking] do |f| %>
      <div class="col-md-auto">
        <%= f.input :first_day_of_booking, label: 'Date de début souhaitée', as: :date, html5: true, order: [:day, :month, :year],
                required: false  %>
      </div>
      <div class="col-md-auto">
        <%= f.input :last_day_of_booking, label: 'Date de fin souhaitée', as: :date, html5: true,order: [:day, :month, :year],
                required: false %>
      </div>
      <div class="col text-center mt-5">
        <%= f.submit "Mettre à jour", class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
</div>

app/views/bookings/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
    <h1 class="display-1">Vos réservations</h1>
  </div>
</div>

<div class="py-5">
  <div class="container">
  <% if @my_bookings.empty? %>
    <p class='text-center mt-5'><strong>Vous n'avez pas encore de réservations</strong></p>
    <% else %>
    <div class="box d-flex flex-column">
    <h2>En cours</h2>
    <% @my_bookings.each do |booking| %>
      <div class="d-flex flex-column card">
        <%= booking.product.title %>
        <%= booking.product.price_per_day %>€/jours
      </div>
    <% end %>
  <% end %>
  <div class="card-wrapper">
    <div class="widget-list row hidden-md-up">
      <% @my_bookings.each do |booking| %>
        <% product = Product.find(booking.product_id) %>
        <div class="shadow card col-md-4 widget">
          <div class="card-header bg-transparent " >
            <ul class="list-inline">
              <li class="list-inline-item">
              <%= link_to product.title, product_path(product) %>
              </li>
              <li class="list-inline-item">
              <%= button_to'╳', booking, method: :delete, data: {turbo_method: :delete}, class:"button" %>
              </li>
            </ul>
          </div>
          <div class="card-body">
            <% if product.photo.key.present? %>
                <%= cl_image_tag booking.product.photo.key, crop: :fill, class:"product_pic card-img-top" %>
              <% else %>
                <%= image_tag("unknown.jpg", class:"product_pic card-img-top") %>
              <% end %>
              <p class="card-title">Ville: <%= product.city %></p>
              <p class="card-subtitle text-muted"><span class="font-weight-bold">Prix ​​total:</span> <%= booking.total_price %> Euros</p>
              <small class="card-text p-y-1"><span class="font-weight-bold">Description:</span> <%= product.description %></small><br>
          </div>
          <div class="card-footer bg-transparent d-flex justify-content-center link_list">
            <%= link_to 'Voir', booking, class: "p-2" %> <br>
            <%= link_to 'Edit', edit_booking_path(booking), class: "p-2" %>
          </div>
        </div>
      <% end %>
      </div>
    </div>
      <div class="row">
        <div class="container text-center">
          <%= link_to "Retour à tous les produits !", products_path, class:"btn btn-outline-primary" %>
          <%= link_to 'Tous vos avis', reviews_path, class: "btn btn-outline-primary" %>
        </div>
      </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h2 class="display-1 pt-5">Mes demandes</h2>
  </div>
</div>

  <h1 class="text-center">Faire une demande de réservation pour <%= @product.title %></h1>
<div class="container d-flex flex-column p-4 mb-4 shadow w-50 mx-auto">
  <h2 class="text-center">Produit : <strong><%= @product.title %></strong></h2>
  <p class="text-center">Description : <%= @product.description %>
    <div class="row">
      <%= simple_form_for [ @product, @booking ] do |f| %>
        <%= f.input  :first_day_of_booking, required: false, label: 'Date de début souhaitée' %>
        <%= f.input :last_day_of_booking, required: false, label: 'Date de fin souhaitée'  %>
        <div class="text-center">
          <%= f.submit "Louer le produit", class: "btn btn-primary w-50" %><br>
          <%= link_to "Retour à tous les produits", products_path, class: "btn btn-primary"  %>
          <%= link_to "Retour à vos réservations", bookings_path(@booking), class: "btn btn-primary"  %>
        </div>
      <% end %>
    </div>
</div>

app/views/bookings/show.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
  <% product = Product.find(@booking .product_id) %>
   <h2 class="display-1 pt-5">Votre reservation a <%= product.city %></h2>
  </div>
</div>

<div class="container">
  <div class="row d-flex align-items-center justify-content-center">
    <div class="info show_booking row ">
      <div class="container">
        <div class="row">
          <div class="col">
            <% if product.photo.key.present? %>
              <%= cl_image_tag product.photo.key, crop: :fill, class:"product_pic" %>
            <% else %>
              <%= image_tag("unknown.jpg", class:"product_pic") %>
            <% end %>
            <p style="font-size: 16px;"><span class="font-weight-bold">From: </span><%= @booking.first_day_of_booking.strftime("%e-%m-%Y")  %></p>
            <p style="font-size: 16px;"><span class="font-weight-bold">To: </span><%= @booking.last_day_of_booking.strftime("%e-%m-%Y")  %></p>
            <p style="font-size: 16px;"><span class="font-weight-bold">Addresse: </span><%= product.address  %></p>
            <p style="font-size: 16px;"><span class="font-weight-bold">Description: </span><%= product.description  %></p>
            <p style="font-size: 16px;"><span class="font-weight-bold">Nombre de piéces: </span><%= product.capacity  %></p>
            <p style="font-size: 16px;"><span class="font-weight-bold">Ville: </span><%= product.city  %></p>
            <p style="font-size: 16px;"><span class="font-weight-bold">Total Price: </span><%= @booking.total_price %> Euros.</p>
          </div>
          <div class="col">
            <% if @booking.review %>
              <div class="card-block p-3">
                <h3>Votre opinion</h3>
                  <div class="card-block p-3">
                    <h4 class="py-4"><%= product.address %></h4>
                    <div class="my-1">
                      <% if @booking.review.rating == 5 %>
                        <div class="d-flex">
                          <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i>
                        </div>
                      <% elsif @booking.review.rating == 4 %>
                        <div class="d-flex">
                          <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i>
                        </div>
                      <% elsif @booking.review.rating == 3 %>
                        <div class="d-flex">
                          <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
                        </div>
                      <% elsif @booking.review.rating == 2 %>
                        <div class="d-flex">
                          <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
                        </div>
                      <% elsif @booking.review.rating == 1 %>
                        <div class="d-flex">
                          <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
                        </div>
                      <% else %>
                        <div class="d-flex">
                          <i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
                        </div>
                      <% end %>
                    </div>
                    <p><%= @booking.review.content %></p>
                    <%= link_to "Votre avis", review_path(@booking.review), class: "btn btn-outline-dark" %>
                  </div>
                </div>
              <% else %>
                <%= link_to 'Ajouter un commentaire', new_booking_review_path(@booking), class: "btn btn-primary mx-2" %>
                <%= link_to 'Retour à vos réservations', bookings_path, class: "btn btn-primary mx-2" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>