config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products, only: %i[destroy]
  root to: 'pages#home'

  # get '/users/sign_out' => 'devise/sessions#destroy'

  get 'my_products', to: 'products#my_products'

  resources :products do
    resources :bookings, only: %i[new create destroy]

    collection do
      get :search
    end

    member do
      get :reviews
    end

    resources :bookings, only: %i[new create destroy]
  end

  resources :bookings, except: [ :new, :index, :create ] do
    resources :reviews, only: [ :new, :create ]
  end

  resources :reviews, except: [ :new, :create ]

  get '/bookings', to: 'bookings#index'

  get '/error', to: 'errors#not_found'

  # get "*path", to: redirect("/error")
end

app/views/shared/_calendar.html.erb
<div class="calendar col-6" id="calendar-data" data-start-date="<%= product.start_date.strftime("%e/%m/%Y") %>" data-end-date="<%= product.end_date.strftime("%e/%m/%Y") %>" >
  <span>Sélectionnez des dates</span>
  <div id="reportrange" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%">
      <i class="fa fa-calendar"></i>&nbsp;
      <span></span> <i class="fa fa-caret-down"></i>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-4">
        <%= link_to root_path do %>
        <%= image_tag 'Logo_Bric2.png', class:"logo"%>
        <% end %>
      </div>
      <div class="col-sm-8 d-flex align-items-center">
        <h2 class="fw-bold">LEGO BRIC </h2>
      </div>
  </div>
    <%# <%= form_with url: products_path, method: :get, class: "d-flex" do %>
      <%#= text_field_tag :query,
        params[:query],
        class: "form-control rounded-pill col-6 me-3",
        placeholder: "Entrez une ville"
      %>
      <%#= submit_tag "Le(t's) go", class: "btn btn-outline-primary rounded-pill col-4" %>
    <%# end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto my-2 my-lg-0 link_list">
        <li class="nav-item">
          <%= link_to 'ACCUEIL', root_path, class:"nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            LOCATION
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Comment ça marche ?</a></li>
            <li><a class="dropdown-item" href="#">Les modèles</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            A PROPOS
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Qui sommes-nous ?</a></li>
            <li><a class="dropdown-item" href="#">Avis clients</a></li>
            <li><a class="dropdown-item" href="#">Sources et technos</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link">CONTACT</a>
        </li>
      </ul>
      <ul class="navbar-nav me-auto link_list">
        <% if user_signed_in? %>
          <li class="nav-item dropdown menu">
            <%= image_tag "sign_in.png", class: "sign-in dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Profil - <%= current_user.name %></a>
              <%= link_to "Mes produits", my_products_path, class: "dropdown-item" %>
              <%= link_to "Ajouter un produit", new_product_path, class: "dropdown-item" %>
              <%= link_to "Mes réservations", bookings_path, class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
          <% else %>
            <li class="nav-item dropdown">
              <%= link_to "CONNEXION", new_user_session_path %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>