config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products, only: %i[destroy]
  root to: 'pages#home'

  # get '/users/sign_out' => 'devise/sessions#destroy'

  get 'my_products', to: 'products#my_products'

  resources :products do
    resources :bookings, only: %i[new create destroy]

    collection do
      get :search
    end

    member do
      get :reviews
    end

    resources :bookings, only: %i[new create destroy]
  end

  resources :bookings, except: [ :new, :index, :create ] do
    resources :reviews, only: [ :new, :create ]
  end

  resources :reviews, except: [ :new, :create ]

  get '/bookings', to: 'bookings#index'

  get '/error', to: 'errors#not_found'

  # get "*path", to: redirect("/error")
end

app/models/product.rb
class Product < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user

  has_many :bookings

  has_one_attached :photo
  has_many :reviews, through: :bookings

  validates :price_per_day, presence: true
  validates :address, presence: true
  validates :capacity, presence: true
  validates :title, presence: true
  # validates :description, presence: true
  # validates :city, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_city_address,
    against: [ :city, :address ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  def average_rating
    if self.bookings.empty?
      return {
        average: 0,
        num: 0
      }
    else
      ratings = []
      number = 0
      self.bookings.each do |booking|
        if booking.review
          number += 1
          ratings << booking.review.rating
        else
          next
        end
      end
      if ratings.empty?
        return {
          average: 0,
          num: 0
        }
      else
        return {
          average: ((ratings.sum) / ratings.count),
          num: number
        }
      end
    end
  end

  def reviews
    reviews = []
    unless self.bookings.empty?
      self.bookings.each do |booking|
        reviews << booking.review if booking.review
      end
    end
    return reviews
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]
  before_action :find_user, :database_search
  before_action :find_product, only: %i[show edit update destroy reviews]

  def index
    @products = Product.all
    # @products = current_user.products.all
    # @products = policy_scope(Product)
    if params[:query].present?
      @products = Product.search_by_city_and_address(params[:query])
    else
      @products = Product.all
    end
      @markers = @products.geocoded.map do |product|
      {
        lat: product.latitude,
        lng: product.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { product: product }),
        marker_html: render_to_string(partial: "marker", locals: {product: product})
      }
    end
  end

  def new
    @product = Product.new
    # @product.user_id = @user.id
    # authorize @product
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = @user.id
    @product = current_user.products.build(product_params)
    # authorize @product
    # if @product.save
    #   redirect_to product_path(@product)
    # else
    #   render :new
    # end
    if @product.save
      flash[:notice] = "Product successfully listed for sale!"
      redirect_to @product
     else
      flash[:alert] = "Failed to list product for sale. Please try again."
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
    @booking = Booking.new
  end

  def edit
  end

  def update
    @product.update(product_params)
    @booking = @product.bookings.find(params[:booking_id])
    redirect_to product_path(@product)
  end

  def destroy
    @product.destroy
    redirect_to my_products_path
  end

  def my_products
    @products = current_user.products
    @bookings = @products.map {|p| p.bookings}.flatten
    # authorize @products
  end

  def search
    if params[:query].present?
      @products = Product.search_by_city_address(params[:query])
    else
      @products = Product.all
    end
    @count = @products.count
    @query = params[:query]

    @markers = @products.geocoded.map do |product|
      {
        lat: product.latitude,
        lng: product.longitude,
        info_window: render_to_string(partial: "info_window", locals: { product: product }),
        marker_html: render_to_string(partial: "marker", locals: {product: product})
      }
    end
    # authorize @products
    # authorize @markers
  end

  def reviews
    unless @product.reviews.empty?
      @reviews = @product.reviews
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :address, :city, :capacity, :price_per_day, :photo)
  end

  def find_product
    if Product.find_by(id: params[:id]).nil?
      redirect_to error_path
    else
      @product = Product.find(params[:id])
      # authorize @product
    end
  end

  def find_user
    @user = current_user
  end

  def database_search
    @markers = Product.all
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_info_window.html.erb
<%= link_to product do %>
  <% if product.photo.key.nil? %>
    <%= image_tag "no-image.png", class:"img-fluid width: 100% height: auto" %>
  <% else %>
    <%= cl_image_tag product.photo.key, crop: :fill, class:"img-fluid width: 100% height: auto" %>
  <% end %>
  <div class="map-card">
    <p><span class="font-weight-bold" ><i class="fa fa-location-arrow"></i></span>  <%= product.address %> <strong><%= product.city %></strong></p>
    <p><span class="font-weight-bold" ><i class="fa fa-user"></i></span>  <%= product.capacity %> people</p>
    <p>€/day <span class="font-weight-bold"><%= product.price_per_day %></span></p>
  </div>
<% end %>

app/views/products/_marker.html.erb
<%= image_tag "Logo_Bric2.png", height: 50, width: 50, alt: "Logo" %>

app/views/products/edit.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h1 class="display-1 pt-5">Ajouter un produits</h1>
  </div>
</div>
<div class="container">
  <div class="rental_form">
    <%= simple_form_for [ @product ] do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :address %>
      <%= f.input :city %>
      <%= f.input :capacity %>
      <%= f.input :price_per_day %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Modifier le produit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h1 class="display-1 pt-5">Ensembles À Louer</h1>
  </div>
</div>

<div class="px-5 products-map-grid">
    <div id='map' style='width: 100%;'
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

    <div class="widget-list row row-cols-3">
  <div class="product-cards p-4">
    <% @products.each do |product| %>
      <div class="shadow card mb-3 widget">
        <div class="card-block p-3">
          <div class="card-body">
            <% if product.photo.attached? %>
              <%= cl_image_tag product.photo.key, class: 'card-img-top index-image' %>
            <% else %>
            <%= image_tag("unknown.jpg", class:"card-img-top my_product_image index-image") %>
            <% end %>
            <h5 class="card-title text-center"><%= link_to product.title, product_path(product) %></h5>
            <p class="card-text"><%= product.price_per_day %> €/ jour</p>
            <%= link_to "Voir le produit", product, class: "rounded-pill btn btn-outline-warning" %>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/products/my_products.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h1 class="display-1">Mes produits</h1>
  </div>
</div>
<div class="card-wrapper">
  <div class="my_products_container">
    <div class="widget-list row row-cols-3 p-4">
      <% unless current_user.products.nil? %>
        <% @products.each do |product|%>
          <div class="shadow card mb-3 widget">
            <div class="card-header bg-transparent " >
              <ul class="list-inline">
                <li class="list-inline-item">
                <%= link_to product.title, product_path(product) %>
                </li>
                <li class="list-inline-item">
                <%= button_to'╳', product_path(product), method: :delete, data: {turbo_method: :delete}, class:"button" %>
                </li>
              </ul>
            </div>
              <div class="card-body">
                <% if product.photo.key.present? %>
                <%= cl_image_tag(product.photo.key, class:"") %>
                <% else %>
                  <%= image_tag("unknown.jpg", class:"") %>
                <% end %>
                <p><%= product.address %></p>
              </div>
            <div class="card-footer bg-transparent">
              <%= link_to 'Modifier le produit', edit_product_path(product), class:"" %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <div class="row">
    <div class="container text-center">
      <%= link_to "Retour à tous les produits !", products_path, class:"btn btn-outline-primary" %>
    </div>
  </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h1 class="display-1 pt-5">Ajouter un produits</h1>
  </div>
</div>

<div class="container">
  <div class="rental_form">
    <%= simple_form_for [ @product ] do |f| %>
      <%= f.input :title, required: false %>
      <%= f.input :description %>
      <%= f.input :price_per_day, required: false %>
      <%= f.input :city %>
      <%= f.input :address, required: false %>
      <%= f.input :capacity, required: false %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Ajouter produits", class: "btn btn-outline-primary" %>
    <% end %>
  </div>
</div>

app/views/products/reviews.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h1 class="display-1 pt-5">Mes avis</h1>
  </div>
</div>

<h1><span class="text-muted"><%= @product.address %></span> Reviews (<%= @product.reviews.count %> opinions)</h1>
<div class="container">
  <div class="row d-flex justify-content-center">
    <% @product.reviews.each do |review| %>
      <div class="review-card col-4 shadow-sm m-2 border">
        <div>
          <% if @product.photo.key.nil? %>
            <%= image_tag "no-image.png", class:"img-fluid width: 100% height: auto" %>
          <% else %>
            <%= cl_image_tag @product.photo.key, class:"img-fluid width: 100% height: auto" %>
          <% end %>

          <div class="my-3 star-rating">
            <% if review.rating == 5 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i>
              </div>
            <% elsif review.rating == 4 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% elsif review.rating == 3 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% elsif review.rating == 2 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% elsif review.rating == 1 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% else %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% end %>
          </div>

          <p><%= review.content %></p>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Back to product', product_path(@product), class: "btn btn-primary" %>
</div>

app/views/products/search.html.erb
<% @search_colon = @query.present? ? ":" : ""  %>
<% @search_text =  @count > 1 || @count == 0 ? "stays" : "stay" %>
<h1 class="text-center">All Available products</h1>
<h3 class="text-center"><%= @query.capitalize %> <%= @search_colon %> <%= @count %> <%=@search_text %> found </h3>
<div class="px-5 products-map-grid">
    <div id='map' style='width: 100%;'
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  <div class="product-cards">
    <% @products.each do |product| %>
    <div>
      <div class="card mb-2">
        <div class="card-block p-3">
          <div class="products-photo">
            <% if product.photo.key.present? %>
              <%= cl_image_tag product.photo.key, class:"card-img-top search-image " %>
            <% else %>
            <%= image_tag("unknown.jpg", class:"card-img-top search-image") %>
            <% end %>
          </div>
          <strong><p class="card-title"><%= product.address %></p></strong>
          <p class="card-subtitle text-muted"><span class="font-weight-bold">Price:</span> <%= product.price %> Euros</p>
          <small class="card-text p-y-1"><span class="font-weight-bold">Capacity:</span> <%= product.capacity %> people</small><br>
          <%= link_to 'Check it out!', product, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<h1><%= link_to "Go back to home page", root_path, class: "btn btn-primary" %></h1>

app/views/products/show.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h1 class="display-1 "><%= @product.title %></h1>
  </div>
</div>
<div class="container">
  <div class="cards mb-3" >
  <div class="row g-0">
    <div class="col-md-4">
      <% if @product.photo.attached? %>
          <%= cl_image_tag @product.photo.key, class: 'card-img-top my_product_image' %>
      <% end %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h1 class="title-inner"><%= @product.title %></h1><br>
        <p class="card-content"><%= @product.description %></p><br>
        <p class="card-content"><%= @product.price_per_day %>€/jour </p>
      </div>
    </div>
  </div>
</div>
<div class="text-decoration-none text-center">
    <%= link_to "Louer", "/products/#{params[:id]}/bookings/new", class: "btn btn-outline-primary" %>
    <%= link_to "Retour aux produits", products_path, class: "btn btn-outline-primary" %>
</div>
</div>
<br>
<br>