config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products, only: %i[destroy]
  root to: 'pages#home'

  # get '/users/sign_out' => 'devise/sessions#destroy'

  get 'my_products', to: 'products#my_products'

  resources :products do
    resources :bookings, only: %i[new create destroy]

    collection do
      get :search
    end

    member do
      get :reviews
    end

    resources :bookings, only: %i[new create destroy]
  end

  resources :bookings, except: [ :new, :index, :create ] do
    resources :reviews, only: [ :new, :create ]
  end

  resources :reviews, except: [ :new, :create ]

  get '/bookings', to: 'bookings#index'

  get '/error', to: 'errors#not_found'

  # get "*path", to: redirect("/error")
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_user
  before_action :find_booking, only: %i[new create]
  before_action :find_review, only: %i[show edit update destroy ]

  def index
    # @reviews = Review.all
    # reviews_all = policy_scope(Review)
    @reviews = reviews_all.select do |review|
      booking = Booking.find(review.booking_id)
      booking.user_id == @user.id
    end
  end

  def new
    @review = Review.new
    # authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.booking_id = @booking.id
    # authorize @review
    @review.save
    if @review.save
      redirect_to review_path(@review)
    else
      render :new
    end
  end

  def show
    # authorize @review
  end

  def edit
    # authorize @review
  end

  def update
    # authorize @review
    @review.update(review_params)

    redirect_to review_path(@review)
  end

  def destroy
    # authorize @review
    @review.destroy
    redirect_to bookings_path
  end

  private

  def find_user
    @user = current_user
  end

  def find_booking
    @booking = Booking.find(params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end

  def find_review
    @review = Review.find(params[:id])
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/edit.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h1 class="display-1 pt-5">Modifier votre avis</h1>
  </div>
</div>

<div class="container">
  <%= simple_form_for [ @review ] do |f| %>
    <%= f.input :rating, collection: [1, 2, 3, 4, 5] %>
    <%= f.input :content, hint: "Modifiez votre commentaire pour cet avis" %>
    <%= f.submit "Modifier l'avis", class: "btn btn-outline-warning" %>
  <% end %>
</div>

app/views/reviews/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h1 class="display-1 pt-5">Mes avis</h1>
  </div>
</div>

<div class="container">
  <div class="row d-flex justify-content-center">
    <% @reviews.each do |review| %>
      <% @booking = Booking.find(review.booking_id) %>
      <% @product = Product.find(@booking.product_id) %>
      <div class="review-card col-4 shadow-sm m-2 border">
        <div>
          <% if @product.photo.key.nil? %>
            <%= image_tag "no-image.png", class:"img-fluid width: 100% height: auto" %>
          <% else %>
            <%= cl_image_tag @product.photo.key, class:"img-fluid width: 100% height: auto" %>
          <% end %>

          <div class="my-3 star-rating">
            <% if review.rating == 5 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i>
              </div>
            <% elsif review.rating == 4 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% elsif review.rating == 3 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% elsif review.rating == 2 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% elsif review.rating == 1 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% else %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% end %>
          </div>

          <p><%= review.content %></p>

          <p>À partir de <strong><%= @booking.first_day_of_booking %></strong> jusq'au <strong><%= @booking.last_day_of_booking %></strong></p>
          <p>Prix ​​total <strong><%= @booking.total_price %>€</strong></p>

          <div>
            <%= link_to "jeter un oil", review_path(review), class: "text-success" %>
            <%= link_to "Modifier", edit_review_path(review), class: "text-warning" %>
            <%= link_to "Suprimer",
            review_path(review),
            method: :delete,
            data: { confirm: "Are you sure?" }, class: "text-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Bookings', bookings_path, class: "btn btn-primary" %>
</div>

app/views/reviews/new.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h1 class="display-1 pt-5">Ajouter un commentaire</h1>
  </div>
</div>

<div class="container">
<% @product = Product.find(@booking.product_id) %>
<h1 class="text-center">Comment s'est passé votre location à <strong><%= @product.address %></strong>?</h1>
  <%= simple_form_for [ @booking, @review ] do |f| %>
    <%= f.input :rating, required: false, collection: [1, 2, 3, 4, 5] %>
    <%= f.input :content, required: false, label: 'Contenu', required: false, hint: "Parlez-nous de votre expérience en #{@product.address}" %>
    <%= f.submit "Ajouter", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/reviews/show.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h1 class="display-1 pt-5">Votre commentaire</h1>
  </div>
</div>

<% @booking = Booking.find(@review.booking_id) %>
<% @product = Product.find(@booking.product_id) %>
<div class="container">
  <div class="d-flex justify-content-around align-items-center">
    <h1>Your <strong class="text-muted"><%= @product.title %></strong> review</h1>

  </div>
  <div class="review-card d-flex row justify-content-around">
    <div class="col-5 d-flex justify-content-around">
      <% if @product.photo.key.nil? %>
        <%= image_tag "no-image.png", class:"review-image" %>
      <% else %>
        <%= cl_image_tag @product.photo.key, class:"review-image" %>
      <% end %>
    </div>
    <div class="col-5 ">
      <div class="star-rating my-3">
        <p>Rating:</p>
        <% if @review.rating == 5 %>
          <div class="d-flex">
            <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i>
          </div>
        <% elsif @review.rating == 4 %>
          <div class="d-flex">
            <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i>
          </div>
        <% elsif @review.rating == 3 %>
          <div class="d-flex">
            <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
          </div>
        <% elsif @review.rating == 2 %>
          <div class="d-flex">
            <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
          </div>
        <% elsif @review.rating == 1 %>
          <div class="d-flex">
            <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
          </div>
        <% else %>
          <div class="d-flex">
            <i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
          </div>
        <% end %>
      </div>
      <p>Comment: <strong><%= @review.content %></strong></p>

      <p>From <strong><%= @booking.first_day_of_booking %></strong> to <strong><%= @booking.last_day_of_booking %></strong></p>
      <p>Total price <strong><%= @booking.total_price %>€</strong></p>

      <div>
        <%= link_to "Edit", edit_review_path(@review), class: "btn btn-primary btn-sm" %>
        <%= link_to "Dlete", review_path(@review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary btn-sm" %>
        <%= link_to "Retour sur votre reservation", booking_path(@booking), class: "btn btn-primary btn-sm" %>
      </div>
    </div>
  </div>
</div>